apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: geneweaver-aon-api
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    gitCommit:
      variant: AbbrevCommitSha
  artifacts:
    - image: geneweaver-aon-api
      context: .
      docker:
          dockerfile: Dockerfile
  local:
    useBuildkit: true
test:
  - image: geneweaver-aon-api
    structureTests:
      - deploy/tests/*
profiles:
  - name: jax-cluster-dev-10--dev
    deploy:
      kustomize:
        paths:
          - deploy/k8s/overlays/jax-cluster-dev-10--dev
  - name: jax-cluster-dev-10--sqa
    deploy:
      kustomize:
        paths:
          - deploy/k8s/overlays/jax-cluster-dev-10--sqa
  - name: jax-cluster-prod-10--stage
    deploy:
      kustomize:
        paths:
          - deploy/k8s/overlays/jax-cluster-prod-10--stage
  - name: jax-cluster-prod-10--prod
    deploy:
      kustomize:
        paths:
          - deploy/k8s/overlays/jax-cluster-prod-10--prod
