"""First commit

Revision ID: 4297df5638d7
Revises: 
Create Date: 2020-12-16 19:27:45.142317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4297df5638d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('taxon_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gene',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('prefix', sa.String(), nullable=True),
    sa.Column('species', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_id')
    )
    op.create_table('ortholog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_gene', sa.Integer(), nullable=True),
    sa.Column('to_gene', sa.Integer(), nullable=True),
    sa.Column('is_best', sa.Boolean(), nullable=True),
    sa.Column('is_best_revised', sa.Boolean(), nullable=True),
    sa.Column('is_best_is_adjusted', sa.Boolean(), nullable=True),
    sa.Column('num_possible_match_algorithms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_gene'], ['gene.id'], ),
    sa.ForeignKeyConstraint(['to_gene'], ['gene.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ortholog_algorithms',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('algorithm_id', sa.Integer(), nullable=True),
    sa.Column('ortholog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithm.id'], ),
    sa.ForeignKeyConstraint(['ortholog_id'], ['ortholog.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ortholog_algorithms')
    op.drop_table('ortholog')
    op.drop_table('gene')
    op.drop_table('species')
    op.drop_table('algorithm')
    # ### end Alembic commands ###
