cat k8s-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: geneweaver-ortholog-normalizer
  labels:
    app: geneweaver-ortholog-normalizer
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: geneweaver-ortholog-normalizer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer